### ISSUE TITLE
Cannot generate signed apk from Panda cordova export

### ISSUE THREAD

**Issue by simsketch** [ekelokorpi/panda-engine#205]
**Describe the bug**
I used `cordova build android --release' to create an apk and it generated android-release-unsigned.apk so I opened it in Android Studio to try and sign it but when I attempt to build I get the following error:

```
Error:Android Source Generator: Error: Can't find bundle for base name messages.AndroidJpsBundle, locale en_US
java.util.MissingResourceException: Can't find bundle for base name messages.AndroidJpsBundle, locale en_US
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:773)
	at org.jetbrains.jps.android.AndroidJpsBundle.getBundle(AndroidJpsBundle.java:22)
	at org.jetbrains.jps.android.AndroidJpsBundle.message(AndroidJpsBundle.java:32)
	at org.jetbrains.jps.android.AndroidSourceGeneratingBuilder.runBuildConfigGeneration(AndroidSourceGeneratingBuilder.java:620)
	at org.jetbrains.jps.android.AndroidSourceGeneratingBuilder.doBuild(AndroidSourceGeneratingBuilder.java:218)
	at org.jetbrains.jps.android.AndroidSourceGeneratingBuilder.build(AndroidSourceGeneratingBuilder.java:114)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1246)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:923)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:995)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:886)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:719)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:371)
	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:178)
	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:138)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:308)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:138)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:235)
	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl.lambda$executeOnPooledThread$0(SharedThreadPoolImpl.java:42)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**To Reproduce**
1. Generate cordova directory from Panda
2. Open terminal in cordova directory and run `cordova build android --release`
3. Open in Android Studio.
4. Select Build>Generate Signed APK

**Expected behavior**
A signed APK to be generated that's ready for upload to Google Play

**Screenshots**
![image](https://user-images.githubusercontent.com/3129129/46152136-61d65f00-c23e-11e8-8a15-3308bb79726e.png)

**Info**
 - OS: macOS High Sierra 10.13.6
 - Version: Panda Engine 2.9.0

**Additional context**
Using Android Studio 3.1.4

**Comment by ekelokorpi** [comment]
Doesn't really sound like Panda issue.
Maybe this can help: https://stackoverflow.com/questions/45365854/android-source-generator-error-cant-find-bundle-for-base-name-messages-androi
